server:
  port: 8888

spring:
  application:
    name: ead-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/juniorjrjl/ead-config-server-repo
          default-label: master

eureka:
  instance:
    hostname: appconfigserver
  client:
    service-url:
      defaultZone: 'http://appserviceregistry:8761/eureka'