server:
  port: 8888

spring:
  application:
    name: ead-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/juniorjrjl/ead-config-server-repo
          default-label: master

ead:
  config-server:
    username: configserver
    password: ead123cs
  service-registry:
    username: serviceregistry
    password: ead123sr

eureka:
  instance:
    hostname: appconfigserver
  client:
    service-url:
      defaultZone: 'http://${ead.service-registry.username}:${ead.service-registry.password}@appserviceregistry:8761/eureka'